project:
  type: book

book:
  title: "SeasonReview2023"
  author: "Stuart Dykes"
  date: "19/11/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - cycloneGabrielle.qmd
    - climateSummary.qmd
    - seasonalPhenology.qmd
    - pestAndDiseaseMonitoring.qmd
    - yieldAndFruitSizePrediction.qmd
    - MaturityManagement.qmd
    - Harvest.qmd
    - ethrelStudy.qmd
    - yieldPerformance.qmd
    - storage.qmd
    - qualityPhytosanitaryPerformance.qmd
    - defectsAndDisorders.qmd
    - packHousePerformance.qmd
    - fruitSizeAndSKUMix.qmd
    - stockOnHandAndInventory.qmd
    - inMarketQuality.qmd
    - summary.qmd
    - references.qmd
    - appendices.qmd

bibliography: 
  - book.bib
  - phytoRef.bib

pdf-engine: lualatex
mainfont: Geograph
monofont: Geograph
sansfont: Geograph
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage[font=scriptsize,labelfont={bf,footnotesize}]{caption}
    
editor: source

